version: '3'

services: 
  app: 
    build:
      context: .
    environment:
      DbContext: "Server=pg,5432;User Id=dev_admin;Password=secret;Database=my_database"
      "KeycloakClientId": "dev"
      "KeycloakClientUrl": "http://keycloak:8080"
      "KeycloakClientSecret": "ZRgv4Zh3ARIMFWjpRo8cLigx4i8Jf1tZ"
      "KeycloakRealm": "master"
    ports:
      - "5001:5001"
    depends_on: 
      - pg
      - keycloak
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "dev_admin"
      POSTGRES_DB: "my_database"
    ports:
      - "5432:5432"
  
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: "admin" 
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
      - "8080:8080"
    